#!/usr/bin/env bash

##############################################################################
##
##  Spectero, Inc
##  Copyright (c) 2018 - All Rights Reserved.
##  https://spectero.com/
##
##  Spectero Management and Configuration for Linux/Unix
##  Variables will need to be replaced by the installer.
##
##############################################################################

DOTNET_BINARY="{dotnet path}"
SPECTERO_WORKING_DIRECTORY="{spectero working directory}"
DAEMON_WORKING_DIRECTORY="$SPECTERO_WORKING_DIRECTORY/$VERSION/daemon"
DAEMON_VERSION="latest"
CLI_WORKING_DIRECTORY="$SPECTERO_WORKING_DIRECTORY/$VERSION/cli"
CLI_BINARY="Spectero.daemon.CLI.dll"


if [ "$1" == "cli" ]; then
	$DOTNET_BINARY $CLI_WORKING_DIRECTORY/$CLI_BINARY
else
	echo "No arguments specified"
	echo "Available commands: 'cli'"
	exit 1
fi
